import { cookies } from 'next/headers';
import Image from 'next/image';
import Link from 'next/link';
import { redirect } from 'next/navigation';
import { getMovies } from '../../database/movies';
import { getValidSessionByToken } from '../../database/sessions';
import UsersForm from './MoviesForm';

export const metadata = {
  title: { default: ' Users Movie ', Template: '%s | Welcome Home' },
  description: 'Generated by create next app',
};

export default async function Movies() {
  const sessionTokenCookie = cookies().get('sessionToken');

  const session =
    sessionTokenCookie &&
    (await getValidSessionByToken(sessionTokenCookie.value));
  if (!session) redirect('/login?returnTo=/users-admin');

  const movie = await getMovies();
  return <UsersForm movie={movie} />;
}
