export const metadata = {
  title: { default: ' Contact| Welcome Home', Template: '%s |  Welcome Home' },
  description: 'Generated by create next app',
};
export default function Contact() {
  return <div>Contact</div>;
}
