export const metadata = {
  title: { default: ' About| Welcome Home', Template: '%s |  Welcome Home' },
  description: 'Generated by create next app',
};
export default function About() {
  return <div>About</div>;
}
