/* import './globals.css'; */

import { Inter, Montserrat } from 'next/font/google';
import { cookies } from 'next/headers';
import Link from 'next/link';
import { useState } from 'react';
import Footer from '../components/Footer/Footer';
import Navbar from '../components/Navbar/Navbar';
import { getUserBySessionToken } from '../database/users';
import LogoutButton from './(auth)/logout/LogoutButton';

const inter = Inter({ subsets: ['latin'] });

const bodyFont = Montserrat({
  subsets: ['latin'],
  weight: ['400', '700', '900'],
});

export const metadata = {
  title: { default: ' Home| Welcome Home', Template: '%s |  Welcome Home' },
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  const cookieStore = cookies();
  const sessionToken = cookieStore.get('sessionToken');

  const user =
    sessionToken && (await getUserBySessionToken(sessionToken.value));

  return (
    <html lang="en">
      {/* <body className={inter.className}>  */}
      <body className={bodyFont.className}>
        {/* <div className="container">
          <div>
            <div className={styles.navLinks}>
              <Link href="/">Home</Link>
              <Link href="/video">Video</Link>
              <Link href="/movies">Movies</Link>
              <Link href="/contact">Contact</Link>
              <Link href="/about">About</Link>
            </div>
          </div>
        </div> */}
        <nav>
          <div>
            {user ? (
              <>
                <div>Hello: {user.username}</div>

                <LogoutButton />
              </>
            ) : (
              <>
                <Link href="/register">Register</Link>
                <br />
                <Link href="/login">Login</Link>
              </>
            )}
          </div>
        </nav>

        <Navbar />

        {children}
        <Footer />
      </body>
    </html>
  );
}
