import { Inter } from 'next/font/google';
import Link from 'next/link';
import Footer from '../components/Footer/Footer';
import Navbar from '../components/Navbar/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: { default: ' Home| Willcome Home', Template: '%s |  Willcome Home' },
  description: 'Generated by create next app',
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/*    <div>
          <Link href="/">Home</Link>
          <Link href="/video">Video</Link>
          <Link href="/movies">Movies</Link>
          <Link href="/contact">Contact</Link>
          <Link href="/about">About</Link>
        </div> */}
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
