/* import './globals.css'; */

import { Inter, Montserrat } from 'next/font/google';
import { cookies } from 'next/headers';
import Link from 'next/link';
import Footer from '../components/Footer/Footer';
import SearchMoviePage from '../components/SearchText/SearchText';
import { getUserBySessionToken } from '../database/users';
import DarkModeToggle from '../LocalStorage';
import LogoutButton from './(auth)/logout/LogoutButton';

const inter = Inter({ subsets: ['latin'] });

const bodyFont = Montserrat({
  subsets: ['latin'],
  weight: ['400', '700', '900'],
});

export const metadata = {
  title: { default: ' Home| Welcome Home', Template: '%s |  Welcome Home' },
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  const cookieStore = cookies();
  const sessionToken = cookieStore.get('sessionToken');

  const user =
    sessionToken && (await getUserBySessionToken(sessionToken.value));

  return (
    <html lang="en">
      <body className={bodyFont.className}>
        <nav className="bg-blue-500 p-4">
          <div className="container mx-auto flex justify-between items-center">
            <div className="text-white">
              {/* Logo with the name "MOVIEDB" */}
              <div className="flex items-center">
                <span className="text-xl font-bold">MOVIEDB</span>
              </div>

              {/* Navigation links */}
              <div className="mt-2">
                <Link href="/" className="mr-4 text-white">
                  Home
                </Link>
                <Link href="/upcoming" className="mr-4 text-white">
                  Upcoming
                </Link>
                <Link href="/movies" className="mr-4 text-white">
                  Trending
                </Link>
                <Link href="/contact" className="mr-4 text-white">
                  Contact
                </Link>
                <Link href="/about" className="mr-4 text-white">
                  About
                </Link>
              </div>
            </div>

            {/* User information and search */}
            <div className="flex items-center">
              <SearchMoviePage />

              {user ? (
                <>
                  <div className="text-white mr-4">Hello: {user.username}</div>
                  <LogoutButton />
                </>
              ) : (
                <>
                  <Link href="/register" className="text-white mr-4">
                    Register
                  </Link>
                  <Link href="/login" className="text-white">
                    Login
                  </Link>
                </>
              )}
            </div>
          </div>
        </nav>

        {children}

        <Footer />
      </body>
    </html>
  );
}
