'use client';
/*
import { CloudinaryContext, Video } from 'cloudinary-react';
import { useRef } from 'react';
import youtube from 'react-youtube';
import styles from './videoplayer.module.css';

export const metadata = {
  title: { default: ' Movies| Welcome Home', Template: '%s |  Welcome Home' },
  description: 'Generated by create next app',
};
export default function VideoPlayer() {
  const videoRef = useRef();
  const cloudName = 'dxaudtsar';
  const videoUrl = 'Video_Background_loop_HD_Free_bkld97';
  return (
    <div>
      <CloudinaryContext cloudName={cloudName}>
        <Video
          publicId={videoUrl}
          width="100%"
          autoPlay
          muted
          loop
          controls="true"
        />
      </CloudinaryContext>
    </div>
  );
}

// Import necessary modules
 */
// VideoPlayer.js

import { CloudinaryContext, Video } from 'cloudinary-react';
import Link from 'next/link';
import { useRef } from 'react';

export const metadata = {
  title: { default: ' Movies| Welcome Home', Template: '%s |  Welcome Home' },
  description: 'Generated by create next app',
};

export default function VideoPlayer() {
  /* const videoRef = useRef(); */
  const cloudName = 'dxaudtsar';
  const videoUrl = 'Video_Background_loop_HD_Free_bkld97';

  return (
    <div className="relative h-screen">
      <CloudinaryContext cloudName={cloudName}>
        <Video
          publicId={videoUrl}
          width="100%"
          autoPlay
          muted
          loop
          controls="true"
          className="w-full h-full object-cover"
        />
      </CloudinaryContext>
      <div
        className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 text-center text-white"
        style={{ fontFamily: "'YourCustomFont', sans-serif" }}
      >
        <h1 className="text-4xl font-bold mb-4">WELCOME TO MOVIEDB</h1>
        {/* Add additional content here if needed */}
        <p className="text-lg mb-8">
          Explore a vast collection of movies at your fingertips. Our MOVIEDB
          brings you a curated selection of the latest releases, timeless
          classics, and hidden gems. Immerse yourself in the world of cinema
          right from the comfort of your home. Whether you're a film buff or
          just looking for something new to watch, our MOVIEDB has something for
          everyone. Enjoy the ultimate cinematic experience with high-quality
          videos and a user-friendly interface. Start your movie journey today!
        </p>
        <Link href="/login">
          <button
            className="bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
            type="submit"
          >
            Login
          </button>
        </Link>
      </div>
    </div>
  );
}
