/* 'use client';
import { CloudinaryContext, Video } from 'cloudinary-react';
import { useRef } from 'react';
import youtube from 'react-youtube';
import styles from './videoplayer.module.css';

export const metadata = {
  title: { default: ' Movies| Welcome Home', Template: '%s |  Willcome Home' },
  description: 'Generated by create next app',
};
export default function VideoPlayer() {
  const videoRef = useRef();
  const cloudName = 'dxaudtsar';
  const videoUrl = 'rhgmrtncemhfhf22schl';
  return (
    <div>
      <CloudinaryContext cloudName={cloudName}>
        <Video publicId={videoUrl} width="550" controls />
      </CloudinaryContext>
      <img
        src="/poster/the iron claw.jpg"
        width={300}
        height={300}
        className={styles.image}
      />
    </div>
  );
}
 */
// Import necessary modules
'use client';
import { useEffect, useState } from 'react';

// Replace 'movie_id' with the actual movie ID you want to fetch
const MovieTrailer = (props) => {
  const [trailerKey, setTrailerKey] = useState(null);
  const movieId = 609681;

  useEffect(() => {
    const fetchData = async () => {
      const options = {
        method: 'GET',
        headers: {
          accept: 'application/json',
          Authorization: 'Bearer your_api_key',
        },
      };

      try {
        const response = await fetch(
          `https://api.themoviedb.org/3/movie/609681/videos?language=en-US`,
          options,
        );
        const data = await response.json();

        // Assuming the first result is a trailer, you may need to adjust this logic
        if (data.results && data.results.length > 0) {
          setTrailerKey(data.results[0].key);
        }
      } catch (error) {
        console.error('Error fetching data:', error);
      }
    };

    fetchData();
  }, []); // Fetch data when the component mounts

  return (
    <div>
      {trailerKey && (
        <div>
          <button
            onClick={() =>
              window.open(
                `https://www.youtube.com/watch?v=${trailerKey}`,
                '_blank',
                'noopener noreferrer',
              )
            }
          >
            Watch Trailer
          </button>
        </div>
      )}
    </div>
  );
};

export default MovieTrailer;
