'use client';
import { CloudinaryContext, Video } from 'cloudinary-react';
import { useRef } from 'react';
import styles from './videoplayer.module.css';

export const metadata = {
  title: { default: ' Movies| Welcome Home', Template: '%s |  Willcome Home' },
  description: 'Generated by create next app',
};
export default function VideoPlayer() {
  const videoRef = useRef();
  const cloudName = 'dxaudtsar';
  const videoUrl = 'rhgmrtncemhfhf22schl';
  return (
    <div>
      <CloudinaryContext cloudName={cloudName}>
        <Video publicId={videoUrl} width="550" controls />
      </CloudinaryContext>
      <img
        src="/images/the iron claw.jpg"
        width={300}
        height={300}
        className={styles.image}
      />
    </div>
  );
}
