import Head from 'next/head';

export const metadata = {
  title: { default: ' Movies| Welcome Home', Template: '%s |  Willcome Home' },
  description: 'Generated by create next app',
};

export default function IndexPage() {
  return (
    <div>
      <Head>
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="/styles.css" />
      </Head>
      <h1>Movies App</h1>
    </div>
  );
}

/* export async function getServerSideProps(context) {
  let trendingMovies = await fetch(
    `https://api.themoviedb.org/3/trending/all/day?language=en-US api_key=${serverRuntimeConfig.apiKey}`);

  trendingMovies await trendingMovies.json()
  return {
    props: {trendingMovies:trendingMovies},
  };
} */
