import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import React from 'react';

/* import { getMovies } from '../../database/movies'; */

export const metadata = {
  title: { default: ' Movies| Welcome Home', Template: '%s |  Willcome Home' },
  description: 'Generated by create next app',
};
const movies = [
  {
    id: 1,
    title: 'Marriage Story',
    type: 'movie',
    genre: 'Comedy, Drama, Romance',
  },
  {
    id: 2,
    title: 'Little Women',
    type: 'movie',
    genre: 'Drama, Family, Romance',
  },
  {
    id: 3,
    title: 'Parasite',
    type: 'movie',
    genre: 'Comedy, Drama, Thriller',
  },
];
export default function MoviesPage() {
  return (
    <div>
      <Head>
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="/styles.css" />
      </Head>
      <h1>Movies App</h1>
      {movies.map((movie) => {
        return (
          <div key={`movie-div-${movie.id}`}>
            <Link href={`/movies/${movie.id}`}>{movie.title}</Link>
            <Image
              src={`/images/${movie.title}.png`}
              alt={movie.title}
              width={200}
              height={200}
            />
          </div>
        );
      })}
    </div>
  );
}
